In [3]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

from matplotlib import pyplot as plt
from IPython.display import display, HTML

from sklearn.metrics import r2_score

In [4]:
X = np.array([8.5, 9.1, 8.8, 9.5, 9.2])
X

array([8.5, 9.1, 8.8, 9.5, 9.2])

In [5]:
y = np.array([20, 25, 22, 33, 27])
y

array([20, 25, 22, 33, 27])

y = Xb<br>
X is a design matrix<br>
b is a vector that holds the slope and intercept<br>

In [6]:
pd.set_option('display.float_format', lambda x: f'{x:.4f}')
myDataFrame = pd.DataFrame(X, columns=['X'])
myDataFrame['y'] = y
myDataFrame

X   y
0 8.5000  20
1 9.1000  25
2 8.8000  22
3 9.5000  33
4 9.2000  27

In [7]:
myDataFrame['ones'] = np.ones(len(X))
myDataFrame

X   y   ones
0 8.5000  20 1.0000
1 9.1000  25 1.0000
2 8.8000  22 1.0000
3 9.5000  33 1.0000
4 9.2000  27 1.0000

In [10]:
design_matrix = myDataFrame[['ones', 'X']]
design_matrix

ones      X
0 1.0000 8.5000
1 1.0000 9.1000
2 1.0000 8.8000
3 1.0000 9.5000
4 1.0000 9.2000

In [11]:
design_matrix_transpose = design_matrix.T
design_matrix_transpose

0      1      2      3      4
ones 1.0000 1.0000 1.0000 1.0000 1.0000
X    8.5000 9.1000 8.8000 9.5000 9.2000

In [12]:
design_matrix_transpose_design_matrix = design_matrix_transpose.dot(design_matrix)
design_matrix_transpose_design_matrix

ones        X
ones  5.0000  45.1000
X    45.1000 407.3900

In [13]:
design_matrix_transpose_design_matrix_inv = np.linalg.inv(design_matrix_transpose_design_matrix)
design_matrix_transpose_design_matrix_inv

array([[138.56802721, -15.34013605],
       [-15.34013605,   1.70068027]])

In [14]:
design_matrix_transpose_y = design_matrix_transpose.dot(y)
design_matrix_transpose_y

ones    127.0000
X      1153.0000
dtype: float64

In [15]:
design_matrix_transpose_design_matrix_inv.dot(design_matrix_transpose_y)

array([-89.03741497,  12.68707483])