In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

from matplotlib import pyplot as plt
from IPython.display import display, HTML

from sklearn.metrics import r2_score

### Data Collection

In [2]:
X = np.array([8.5, 9.1, 8.8, 9.5, 9.2])
X

array([8.5, 9.1, 8.8, 9.5, 9.2])

In [3]:
y = np.array([20, 25, 22, 33, 27])
y

array([20, 25, 22, 33, 27])

### Design Matrix

In [4]:
pd.set_option('display.float_format', lambda x: f'{x:.4f}')
myDataFrame = pd.DataFrame(X, columns=['X'])
myDataFrame['y'] = y
myDataFrame

X   y
0 8.5000  20
1 9.1000  25
2 8.8000  22
3 9.5000  33
4 9.2000  27

In [5]:
myDataFrame['ones'] = np.ones(len(X))
myDataFrame

X   y   ones
0 8.5000  20 1.0000
1 9.1000  25 1.0000
2 8.8000  22 1.0000
3 9.5000  33 1.0000
4 9.2000  27 1.0000

In [6]:
design_matrix = myDataFrame[['ones', 'X']]
design_matrix

ones      X
0 1.0000 8.5000
1 1.0000 9.1000
2 1.0000 8.8000
3 1.0000 9.5000
4 1.0000 9.2000

### Finding Coefficient and Intercept

In [7]:
theta = np.linalg.inv(design_matrix.T.dot(design_matrix)).dot(design_matrix.T).dot(y)
coefficient, intercept = theta
print(f"Coefficient: {coefficient}")
print(f"Intercept: {intercept}")

Coefficient: -89.03741496601135
Intercept: 12.687074829934822


### Finding Coefficient and Intercept using Gradient Descent Method

https://www.geeksforgeeks.org/gradient-descent-in-linear-regression/

In [8]:
X

array([8.5, 9.1, 8.8, 9.5, 9.2])

In [9]:
y

array([20, 25, 22, 33, 27])

#### Standardization

In [10]:
X_mean = np.mean(X)
X_mean

np.float64(9.020000000000001)

In [11]:
X_std = np.std(X)
X_std

np.float64(0.3429285639896447)

In [12]:
X_scaled = (X - X_mean) / X_std
X_scaled

array([-1.51635079,  0.23328474, -0.64153303,  1.39970842,  0.52489066])

#### Designed Matrix

In [13]:
pd.set_option('display.float_format', lambda x: f'{x:.8f}')
myDataFrame = pd.DataFrame(X_scaled, columns=['X'])
myDataFrame['y'] = y
myDataFrame

X   y
0 -1.51635079  20
1  0.23328474  25
2 -0.64153303  22
3  1.39970842  33
4  0.52489066  27

In [14]:
myDataFrame['ones'] = np.ones(len(X))
myDataFrame

X   y       ones
0 -1.51635079  20 1.00000000
1  0.23328474  25 1.00000000
2 -0.64153303  22 1.00000000
3  1.39970842  33 1.00000000
4  0.52489066  27 1.00000000

In [15]:
design_matrix = myDataFrame[['ones', 'X']]
design_matrix

ones           X
0 1.00000000 -1.51635079
1 1.00000000  0.23328474
2 1.00000000 -0.64153303
3 1.00000000  1.39970842
4 1.00000000  0.52489066

In [16]:
y = myDataFrame[['y']]
y

y
0  20
1  25
2  22
3  33
4  27

In [17]:
theta = np.zeros(2)
theta

array([0., 0.])

In [18]:
alpha = 0.1 # learning rate
alpha

0.1

In [19]:
iterations = 1000 # number of iterations
iterations

1000

In [20]:
def predict(X, theta):
    y_pred = X.dot(theta)
    return y_pred

In [21]:
def compute_cost(X, y, theta):
    y_pred = predict(X, theta)
    # mean of sum of square of error
    # 1/len(y) * np.sum(np.square(y_pred - y))
    # for gradient function they need mean of sum of error
    # in that case we divide it by 2 * len(y) instead of dividing it by len(y)
    # derivative of x ** 2 is 2x
    cost = (1/(2 * len(y))) * np.sum(np.square(y_pred - y))
    return cost

In [22]:
def gradient_descent(X, y, theta, iterations):
    cost_history = np.zeros(iterations)
    for i in range(iterations):
        predictions = predict(X, theta)
        # let us calculate the gradient
        # gradient = Xᵀ * error / m
        gradient = 1/len(y) * alpha * (X.T.dot(predictions - y))
        # update the theta
        # theta = theta - learning_rate x gradient
        theta = theta - gradient
        # theta = theta - 1/len(y) * alpha * X.T.dot(predictions - y)
        cost_history[i] = compute_cost(X, y, theta)
    return theta, cost_history

In [23]:
theta_final, cost_history = gradient_descent(design_matrix, y.to_numpy().flatten(), theta, iterations)
theta_final

ones   25.40000000
X       4.35076035
dtype: float64

In [24]:
intercept = theta_final.iloc[1] / X_std
intercept

np.float64(12.687074829931971)

In [27]:
coefficient = theta_final.iloc[0] - intercept * X_mean
coefficient

np.float64(-89.03741496598639)

In [26]:
cost_history

array([269.61153401, 218.50987656, 177.11753403, 143.58973658,
       116.43222064,  94.43463273,  76.61658653,  62.1839691 ,
        50.49354899,  41.02430869,  33.35422405,  27.1414555 ,
        22.10911297,  18.03291552,  14.73119558,  12.05680244,
         9.89054399,   8.13587464,   6.71459247,   5.56335392,
         4.63085069,   3.87552307,   3.2637077 ,   2.76813725,
         2.36672519,   2.04158141,   1.77821496,   1.56488813,
         1.3920934 ,   1.25212967,   1.13875904,   1.04692884,
         0.97254637,   0.91229658,   0.86349424,   0.82396435,
         0.79194514,   0.76600957,   0.74500177,   0.72798545,
         0.71420222,   0.70303782,   0.69399464,   0.68666968,
         0.68073645,   0.67593054,   0.67203775,   0.66888459,
         0.66633053,   0.66426174,   0.66258603,   0.6612287 ,
         0.66012926,   0.65923871,   0.65851737,   0.65793308,
         0.65745981,   0.65707646,   0.65676595,   0.65651443,
         0.6563107 ,   0.65614568,   0.65601202,   0.65